export const OUR_CATALOGUES = [
  {
    id: 1,
    title: "Porsche 911",
    subtitle: "Turbo S",
    price: "189 900 €",
    km: "15 000 km",
    year: "2023",
    fuel: "Essence",
    trans: "Auto",
    img: "/images/main/features/feature-1.jpg",
  },
  {
    id: 2,
    title: "Audi",
    subtitle: "RS3 Sportback",
    price: "75 500 €",
    km: "25 000 km",
    year: "2022",
    fuel: "Essence",
    trans: "Auto",
    img: "/images/main/features/feature-2.jpg",
  },
  {
    id: 3,
    title: "BMW",
    subtitle: "M4 Competition",
    price: "95 800 €",
    km: "18 500 km",
    year: "2023",
    fuel: "Essence",
    trans: "Manual",
    img: "/images/main/features/feature-3.jpg",
  },
  {
    id: 4,
    title: "Mercedes-Benz",
    subtitle: "AMG GT 63 S",
    price: "165 000 €",
    km: "8 200 km",
    year: "2024",
    fuel: "Essence",
    trans: "Auto",
    img: "/images/main/features/feature-1.jpg",
  },
  {
    id: 5,
    title: "Tesla",
    subtitle: "Model S Plaid",
    price: "135 000 €",
    km: "12 000 km",
    year: "2023",
    fuel: "Électrique",
    trans: "Auto",
    img: "/images/main/features/feature-2.jpg",
  },
  {
    id: 6,
    title: "Lamborghini",
    subtitle: "Huracán EVO",
    price: "245 000 €",
    km: "5 500 km",
    year: "2024",
    fuel: "Essence",
    trans: "Auto",
    img: "/images/main/features/feature-3.jpg",
  },
  {
    id: 7,
    title: "Ferrari",
    subtitle: "F8 Tributo",
    price: "289 000 €",
    km: "3 200 km",
    year: "2024",
    fuel: "Essence",
    trans: "Auto",
    img: "/images/main/features/feature-1.jpg",
  },
  {
    id: 8,
    title: "Aston Martin",
    subtitle: "DB11 V12",
    price: "198 500 €",
    km: "11 800 km",
    year: "2023",
    fuel: "Essence",
    trans: "Auto",
    img: "/images/main/features/feature-2.jpg",
  },
  {
    id: 9,
    title: "McLaren",
    subtitle: "570S Spider",
    price: "175 900 €",
    km: "9 500 km",
    year: "2022",
    fuel: "Essence",
    trans: "Auto",
    img: "/images/main/features/feature-3.jpg",
  },
  {
    id: 10,
    title: "Maserati",
    subtitle: "MC20 Coupé",
    price: "235 000 €",
    km: "2 100 km",
    year: "2024",
    fuel: "Essence",
    trans: "Auto",
    img: "/images/main/features/feature-1.jpg",
  },
  {
    id: 11,
    title: "Bentley",
    subtitle: "Continental GT",
    price: "225 800 €",
    km: "14 200 km",
    year: "2023",
    fuel: "Hybride",
    trans: "Auto",
    img: "/images/main/features/feature-2.jpg",
  },
  {
    id: 12,
    title: "Rolls-Royce",
    subtitle: "Wraith Black Badge",
    price: "385 000 €",
    km: "6 800 km",
    year: "2023",
    fuel: "Essence",
    trans: "Auto",
    img: "/images/main/features/feature-3.jpg",
  },
  {
    id: 13,
    title: "Jaguar",
    subtitle: "F-Type R",
    price: "89 500 €",
    km: "22 000 km",
    year: "2022",
    fuel: "Essence",
    trans: "Auto",
    img: "/images/main/features/feature-1.jpg",
  },
  {
    id: 14,
    title: "Bugatti",
    subtitle: "Chiron Sport",
    price: "2 950 000 €",
    km: "1 200 km",
    year: "2024",
    fuel: "Essence",
    trans: "Auto",
    img: "/images/main/features/feature-2.jpg",
  },
  {
    id: 15,
    title: "Koenigsegg",
    subtitle: "Regera",
    price: "1 850 000 €",
    km: "800 km",
    year: "2023",
    fuel: "Hybride",
    trans: "Auto",
    img: "/images/main/features/feature-3.jpg",
  },
];
