export const FRANCHISE = [
  {
    id: 1,
    name: "Drive Paris",
    address: "12 Rue de la Boulnay, Paris",
    phone: "+33 6 53 95 53 12",
    img: "/images/franchise/franchise1.png",
  },
  {
    id: 2,
    name: "Drive Lyon",
    address: "25 Avenue des Champs, Lyon",
    phone: "+33 4 78 92 34 56",
    img: "/images/franchise/franchise1.png",
  },
  {
    id: 3,
    name: "Drive Marseille",
    address: "18 Boulevard Michelet, Marseille",
    phone: "+33 4 91 55 87 32",
    img: "/images/franchise/franchise1.png",
  },
  {
    id: 4,
    name: "Drive Toulouse",
    address: "42 Rue de la République, Toulouse",
    phone: "+33 5 61 23 45 67",
    img: "/images/franchise/franchise1.png",
  },
  {
    id: 5,
    name: "Drive Nice",
    address: "7 Promenade des Anglais, Nice",
    phone: "+33 4 93 87 65 43",
    img: "/images/franchise/franchise1.png",
  },
  {
    id: 6,
    name: "Drive Cannes",
    address: "15 La Croisette, Cannes",
    phone: "+33 4 93 39 78 21",
    img: "/images/franchise/franchise1.png",
  },
  {
    id: 7,
    name: "Drive Bordeaux",
    address: "33 Cours de l'Intendance, Bordeaux",
    phone: "+33 5 56 44 88 77",
    img: "/images/franchise/franchise1.png",
  },
  {
    id: 8,
    name: "Drive Monaco",
    address: "1 Avenue des Beaux Arts, Monaco",
    phone: "+377 93 50 12 34",
    img: "/images/franchise/franchise1.png",
  },
  {
    id: 9,
    name: "Drive Neuilly",
    address: "89 Avenue Charles de Gaulle, Neuilly",
    phone: "+33 1 46 24 67 89",
    img: "/images/franchise/franchise1.png",
  },
  {
    id: 10,
    name: "Drive Versailles",
    address: "12 Avenue de Paris, Versailles",
    phone: "+33 1 39 50 33 44",
    img: "/images/franchise/franchise1.png",
  },
  {
    id: 11,
    name: "Drive Saint-Tropez",
    address: "8 Port de Saint-Tropez, Saint-Tropez",
    phone: "+33 4 94 97 11 22",
    img: "/images/franchise/franchise1.png",
  },
  {
    id: 12,
    name: "Drive Paris 16",
    address: "45 Avenue Foch, Paris 16",
    phone: "+33 1 44 17 98 76",
    img: "/images/franchise/franchise1.png",
  },
];
